
# This is a basic workflow to help you get started with Actions

name: COMPILE ON WEB

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: debian-bullseye
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib -y
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install format
          haxelib install hscript-ex
          haxelib install newgrounds
          haxelib install colyseus
          haxelib install colyseus-websocket
          haxelib install hxcs
          haxelib install polymod
          haxelib install flixel-addons
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git firetongue https://github.com/larsiusprime/firetongue
          haxelib run lime build html5 -debug
          
      - uses: actions/upload-artifact@v2
        with:
          name: yass slay
          path: export/debug/html5/bin
